name: Continuous Integration
on: 
  push:
    paths-ignore:
      - 'README.md'
      - 'Vagrantfile'
      - 'documentation/**'

  pull_request:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'Vagrantfile'
      - 'documentation/**'


jobs:    
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: browser-actions/setup-geckodriver@latest
    - run: geckodriver --version
    - uses: actions/checkout@v2
    - run: docker build --target test --tag my-test-image .
    - run: docker run --env-file .env.test  my-test-image tests
    - run: docker run -e SECRET_KEY=secret -e MONGO_DB_NAME=e2e_db -e MONGO_CONNECT=${{secrets.MONGO_CONNECT}} -e MONGO_COLLECTION_NAME=${{secrets.MONGO_COLLECTION_NAME}} -e MONGO_DEFAULT_STATUS=${{secrets.MONGO_DEFAULT_STATUS}} my-test-image tests_e2e
  publish:
    name: Push Image to dockerhub
    needs: build
    runs-on: ubunto-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker build --target production --tag joeosbo/devopsproj/todo_app:latest
    - run: docker push joeosbo/devopsproj/todo_app --all-tags
##Commenting out as still causing issues
  deploy:
    name: Deploy build package to Azure
    needs: publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code
    - uses: curl -dH -X POST ${{ secrets.AZURE_WEBHOOK }}
   